import Navbar from "../components/Navbar";
import "./globals.css";
import icon from "./../public/images/Icon 1.png"
import { jost, cormorant } from "./fonts";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${jost.variable} ${cormorant.variable} min-h-full flex flex-col`} cz-shortcut-listen="true">
        <Navbar icon={icon} />
        {children}
      </body>
    </html>
  );
}
