import Navbar from "../components/Navbar";
import "./globals.css";
import icon from "./../public/images/icon-1.png"
import { jost, cormorant } from "./fonts";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${cormorant.variable} antialiased`} cz-shortcut-listen="true">
        <a href="#main" className="sr-only focus:not-sr-only">
          Skip to content
        </a>

        <Navbar icon={icon} />

        <main id="main" className="min-h-screen flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
